#!/bin/bash

BASE_DIR=../..

cd $BASE_DIR/RT
if [ ! -e libraytrace.a ]; then
   make -j8
fi
cd -

cd $BASE_DIR/kernels
if [ ! -e libkernels.a ]; then
   make -j8
fi
cd -

cd $BASE_DIR/objects
if [ ! -e libshapes.a ]; then
   make -j8
fi
cd -

cd $BASE_DIR/utilities
if [ ! -e libutils.a ]; then
   make -j8
fi
cd -

make -j8
